### ISSUE TITLE
CTRL+V doesnt work anymore un firefox 63

### ISSUE THREAD

**Issue by mdz0r** [peclik/clipboard_image_paste#77] opened 2018-10-26 17:04 UTC
![47553653-e7196600-d907-11e8-8bf7-7ca2e546da61](https://user-images.githubusercontent.com/42241744/47581466-c0801d00-d951-11e8-87e5-7997e475902b.png)
Hello,
The plugin doesnt work anymore in firefox 63.
Please see attached screenshot!

**Comment by ilpssun** [comment] 2018-10-29 10:40
@mdz0r I am experiencing the same error message `TypeError: pasteCatcher is undefined`.  But it is definitely not an error in Firefox 63 as I can paste in one Redmine instance but not the other.

Working redmine instance:

    Environment:
      Redmine version                3.4.4.stable.17194
      Ruby version                   2.4.1-p111 (2017-03-22) [x86_64-linux]
      Rails version                  4.2.8
      Environment                    production
      Database adapter               Mysql2
      HTTP/S?                        HTTP

Not working in this redmine instance:

    Environment:
      Redmine version                3.4.6.stable.17598
      Ruby version                   2.5.1-p57 (2018-03-29) [x86_64-linux]
      Rails version                  4.2.10
      Environment                    production
      Database adapter               Mysql2
      HTTP/S?                        HTTPS

Plugins are identical in the two instances.  I have not yet had time to dig further into the issue.

**Comment by mdz0r** [comment] 2018-10-29 10:49
I guess it's related to Firefox63 because it was working with FF62 on the same redmine instance.
Chrome 70 is working fine too.

**Comment by ilpssun** [comment] 2018-10-29 11:33
Possible duplicate of #69

**Comment by ilpssun** [comment] 2018-10-29 13:56
There might be a fix already in #78.

**Comment by iquiw** [comment] 2018-10-30 06:07
> Plugins are identical in the two instances. I have not yet had time to dig further into the issue.

@ilpssun I think the difference is whether `HTTP` or `HTTPS`.  `window.Clipboard` is defined only with `HTTPS` (I don't know why), which causes this issue.

**Comment by mdz0r** [comment] 2018-10-31 10:50
> 
> 
> There might be a fix already in #78.

Working for me, thanks!

**Comment by ilpssun** [comment] 2018-11-02 07:35
I got around to testing #78 as well and it has fixed the issue for me, too.

**Comment by peclik** [comment] 2018-11-08 19:07
Thanks to all for reporting and testing.

**Closed by peclik** 2018-11-08 19:07 UTC
